"""Initial commit

Revision ID: 04cd62869edb
Revises: 
Create Date: 2023-09-13 10:05:36.357863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04cd62869edb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_or_facility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('reporting_period',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_month', sa.String(length=50), nullable=False),
    sa.Column('end_month', sa.String(length=50), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=False),
    sa.Column('end_year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('emission_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('co2_emissions_solar', sa.Float(), nullable=False),
    sa.Column('total_emissions', sa.Float(), nullable=False),
    sa.Column('cost_savings', sa.Float(), nullable=False),
    sa.Column('reporting_period_id', sa.Integer(), nullable=False),
    sa.Column('business_or_facility_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['business_or_facility_id'], ['business_or_facility.id'], ),
    sa.ForeignKeyConstraint(['reporting_period_id'], ['reporting_period.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emission_report')
    op.drop_table('user')
    op.drop_table('reporting_period')
    op.drop_table('business_or_facility')
    # ### end Alembic commands ###
